name: Ark Backup Handler Build And Release
 
on:
  push:
    branches:
      - prod
 
env:
 Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands
      
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore "Ark Backup Handler.sln"
 
    - name: Build and Publish Web App
      run: msbuild "Ark Backup Handler.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: D:\a\Ark-Backup-Handler\Ark-Backup-Handler\Ark-Backup-Handler\bin\Release\net6.0-windows\
      
    - name: Rename Folder
      run: |
       cd D:\a\Ark-Backup-Handler\Ark-Backup-Handler\Ark-Backup-Handler\bin\Release\
       ren net6.0-windows "Ark Backup Handler Stable"
      
    - name: Create archive
      run: Compress-Archive -Path "D:\a\Ark-Backup-Handler\Ark-Backup-Handler\Ark-Backup-Handler\bin\Release\Ark Backup Handler Stable\" -DestinationPath "D:\a\Ark-Backup-Handler\Ark-Backup-Handler\Ark-Backup-Handler\bin\Release\Ark Backup Handler Stable\Ark.Backup.Handler.zip"
 
    - name: Read version from XML file
      id: getxmlversion
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'Ark-Backup-Handler\Ark Backup Handler.csproj'
        xpath: '//PropertyGroup//Version'
        
    - name: Read release notes from XML file
      id: getxmlchangenotes
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
       xml-file: 'Ark-Backup-Handler\Ark Backup Handler.csproj'
       xpath: '//PropertyGroup//PackageReleaseNotes'

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.getxmlversion.outputs.info }}
        release_name:  Ark Backup Handler v${{ steps.getxmlversion.outputs.info }}
        body: ${{ steps.getxmlchangenotes.outputs.info }}
        draft: false
        prerelease: true

    - name: Update release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  
        asset_path: 'D:\a\Ark-Backup-Handler\Ark-Backup-Handler\Ark-Backup-Handler\bin\Release\Ark Backup Handler Stable\Ark.Backup.Handler.zip'
        asset_name: Ark.Backup.Handler.Stable.zip
        asset_content_type: application/zip
